server:
  servlet:
    context-path: /as
  forward-headers-strategy: framework
spring:
  sleuth:
    sampler:
      probability: ${OTEL_SAMPLER_PROBABILITY:1.0} # Valid values [0.0 - 1.0]
  jpa:
    # TODO fix mapping issue and set back to open-in-view: false
    open-in-view: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
      pubsub:
        topic: ${PUB_SUB_TOPIC}
        enabled: ${ENABLE_PUB_SUB}
        subscriber:
          fully-qualified-name: ${PUB_SUB_TOPIC_SUBSCRIPTION}
  jackson:
    serialization:
      write-dates-with-zone-id: true
      write-dates-as-timestamps: false
    deserialization:
      adjust_dates_to_context_time-zone: false
  config:
    import: sm://

management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origins: ${ALLOWED_ORIGINS}
        allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allowed-headers: "*"

auth:
  token-filter:
    self-signed:
      issuer: dsgov
      public-key: ${SELF_SIGN_PUBLIC_KEY}
  token-client:
    self-signed:
      issuer: dsgov
      private-key: ${SELF_SIGN_PRIVATE_KEY}
      roles: "um:application-client"

cerbos:
  uri: ${CERBOS_URI}

userManagement:
  baseUrl: "http://user-management/um"

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# These keys are purely utilized in a unit test context.
# Do not use these anywhere else.
auth:
  token-filter:
    self-signed:
      issuer: dsgov
      public-key: |-
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjRRAY61hX6KKu9I6PTmKTYv4z
        kVFUHVvDoDNheVEskrNyEMVJH7FMKBTxRUWgGAWwtPUQ5S+2OowJzBpHl+M1D3HY
        0PLznTmqwZtlOj+NG4+J+Ndu6APBJFLndlWBJrFAjQW8bJtm78I3eyjZeezCFvhG
        iX882R81aatL0qUqtQIDAQAB
        -----END PUBLIC KEY-----

  token-client:
    self-signed:
      issuer: dsgov
      private-key: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQCjRRAY61hX6KKu9I6PTmKTYv4zkVFUHVvDoDNheVEskrNyEMVJ
        H7FMKBTxRUWgGAWwtPUQ5S+2OowJzBpHl+M1D3HY0PLznTmqwZtlOj+NG4+J+Ndu
        6APBJFLndlWBJrFAjQW8bJtm78I3eyjZeezCFvhGiX882R81aatL0qUqtQIDAQAB
        AoGAaRYcpE1mUT605zMVRvvGyuKehwZzeFZlJ+bG62gwbSYHRdWxhb1WWpQ51okl
        pUOQ9gmi6rr5GKtaUzwBdi8213pSoCyY1yuJ6c5HHHP7ZIlbBmhMZpIcIVfVcdB+
        SOvRnE+JB+ByVGIcTzByFnPIiqjiuvX3/WAPzKvygEPLYUkCQQDamlnLFPDuFwEx
        Z6RYsA5c1AaQejaYU8bKV2OWe8CsPbYYb7UYPf4C+uRffl+a/mYg/uEJBxSS8/Pc
        fRH54pw3AkEAvzNpz4UQxh4zGK/iElG/HqxFAs01/WaF1xhO7er0bYVxhGr3jbDa
        TVsCrYsYHPY1sY6C4iY00wi4Jvj2srvycwJAWd0LvqU8KdQBJIsjj2XIcbajgC8N
        VG9UEAf+o3T6DpRL0B3Tx0RssFLtIKh1quSbnULJxYlIluR8Qg6UHjJe3wJAJmBJ
        Yo+QuFMjalcTBx5FQADPsSpDJeNIBc4pOXOpL7pS+IMHwPa4OkKEHRUH9/gq+sJh
        3sZQX/MmExxxV5qFpQJBAJW54aVt5weRviljBfGYTO07OJZcajvUu3BZHig9iW9R
        1pYN2217CXQBxBrA/L6OoodLiaojj7rmsF/25Ipzgmc=
        -----END RSA PRIVATE KEY-----
      
      roles: "um:application-client"
