apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: audit-event
  rules:
    - actions: ["view"]
      roles:
        - event-reader
      effect: EFFECT_ALLOW

    - actions: ["create"]
      roles:
        - event-reporter
      effect: EFFECT_ALLOW

