apiVersion: v1
kind: Service
metadata:
  name: audit-service-postgres
  namespace: {{ .Values.namespace | default "dsgov" }}
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30203
  sessionAffinity: None
  type: NodePort